[server]
headless = true
port = $PORT
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#ff6347"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
